#!/bin/bash

# .git/hooks/pre-receive

SCRIPTPATH=$(dirname $(realpath -s $0))

while read oldrev newrev ref
do
    echo "Ref $ref received. Checking for pre-receive hook modification..."
    if [[ $(! git diff --name-only $oldrev $newrev | grep pre-receive) ]]; then
        echo "Updated pre-receive hook detected. Installing..."
        mkdir -p /tmp/newrev
        git archive $newrev | tar -x -C /tmp/newrev
        mv /tmp/newrev/pre-receive $SCRIPTPATH/pre-receive
        rm -rf /tmp/newrev
        echo "Running new pre-receive hook."
        echo "$oldrev $newrev $ref" | $SCRIPTPATH/pre-receive
        echo "Done running new pre-receive hook."
        exit $?
    else
        echo "No pre-receive hook modification."
    fi
    echo "Ref $ref received. Checking for post-receive hook modification..."
    if [[ $(! git diff --name-only $oldrev $newrev | grep post-receive) ]]; then
        echo "Updated post-receive hook detected. Installing..."
        mkdir -p /tmp/newrev
        git archive $newrev | tar -x -C /tmp/newrev
        mv /tmp/newrev/post-receive $SCRIPTPATH/post-receive
        rm -rf /tmp/newrev
    else
        echo "No post-receive hook modification."
    fi
done
