---

server-port: 8080
static:
  /style.css:
    path: static/style.css
    type: text/css
templates:
  - name: index
    path: templates/index.html
  - name: commit
    path: templates/commit.html
  - name: inline_commit
    path: templates/inline_commit.html
  - name: repository
    path: templates/repository.html
  - name: inline_repository
    path: templates/inline_repository.html
repositories:
  - name: auto-plow
    description: "A wheelchair motor-propelled battery-powered ESP32-driven remote control snow plow."
    branch: dev
    allows:
      - master
      - dev
    github: "https://github.com/JoshuaS3/auto-plow"
    location:
      dev: "/home/josh/repos/auto-plow/.git"
      prod: "/home/git/auto-plow.git"
  - name: joshstock.in
    description: "Source for serving and static templating/compiling of https://joshstock.in."
    branch: master
    github: "https://github.com/JoshuaS3/joshstock.in"
    location:
      dev: "/home/josh/repos/joshstock.in/.git"
      prod: "/home/git/joshstock.in.git"
  - name: ncurses-minesweeper
    description: "Terminal game of Minesweeper, implemented in C with ncurses."
    branch: master
    github: "https://github.com/JoshuaS3/ncurses-minesweeper"
    location:
      dev: "/home/josh/repos/ncurses-minesweeper/.git"
      prod: "/home/git/ncurses-minesweeper.git"
  - name: lognestmonster
    description: "A general-purpose single-header C logging library and parser for event-based logs."
    branch: dev
    allows:
      - master
      - dev
    github: "https://github.com/JoshuaS3/lognestmonster"
    location:
      dev: "/home/josh/repos/lognestmonster/.git"
      prod: "/home/git/lognestmonster.git"
