#!/usr/bin/env bash

SCRIPTPATH=$(dirname $(realpath -s $0))

usage() {
	echo "usage: sudo ./copynginx [prod | test]"
	exit 1
}
if [ "$EUID" -ne 0 ]; then
	echo "error: must run as root"
	usage
fi
if [ $# -eq 0 ]; then
	usage
fi
if [ "$1" != "prod" ] && [ "$1" != "test" ]; then
	usage
fi

if [ ! -f $SCRIPTPATH/nginx.conf ]; then
	echo "error: $SCRIPTPATH/nginx.conf is nonexistent"
	exit 1
fi
echo -e "copying nginx.conf"
cp -v $SCRIPTPATH/nginx.conf /etc/nginx/nginx.conf

if [ -d /etc/nginx/conf.d/ ]; then
	echo -e "clearing /etc/nginx/conf.d/"
	rm -rv /etc/nginx/conf.d
fi

if [ -d /etc/nginx/sites-enabled/ ]; then
	echo -e "clearing /etc/nginx/sites-enabled/"
	rm -rv /etc/nginx/sites-enabled
fi

if [ -d /etc/nginx/env/ ]; then
	echo -e "clearing /etc/nginx/env/"
	rm -rv /etc/nginx/env
fi

if [ ! -d $SCRIPTPATH/$1 ]; then
	echo -e "error: $SCRIPTPATH/$1 is nonexistent"
	exit 1
fi
echo -e "copying $1 configuration"
cp -rv $SCRIPTPATH/$1/* /etc/nginx

echo -e "attempting to reload nginx"
service nginx reload

echo -e "done"
